"""update user, thread and message

Revision ID: 91dc1efc8a8b
Revises: 873ccb2cdf64
Create Date: 2025-11-09 16:49:34.698098+00:00

"""
from typing import Sequence, Union

from alembic import op # noqa: F401
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '91dc1efc8a8b'
down_revision: Union[str, Sequence[str], None] = '873ccb2cdf64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
