"""update inbox and tag

Revision ID: abe7077f90f9
Revises: 91dc1efc8a8b
Create Date: 2025-11-11 09:53:41.645675+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe7077f90f9'
down_revision: Union[str, Sequence[str], None] = '91dc1efc8a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('inbox_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tags', 'inboxes', ['inbox_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'inbox_id')
    # ### end Alembic commands ###
